[project]
name = "workarea-pumptech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "influxdb-client>=1.49.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
